### ISSUE TITLE
Daemon Issues With getting time zone

### ISSUE THREAD

**Issue by braddevans** [ccarney16/pterodactyl-docker#12]
```
20:29:03.043Z  INFO wings: + ------------------------------------ +
20:29:03.045Z  INFO wings: | Running Pterodactyl Daemon v0.6.12    
20:29:03.046Z  INFO wings: |        https://pterodactyl.io        |
20:29:03.046Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
20:29:03.046Z  INFO wings: + ------------------------------------ +
20:29:03.046Z  INFO wings: Loading modules, this could take a few seconds.
20:29:03.614Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
20:29:03.728Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.
20:29:03.733Z  INFO wings: Configuring timezone file location...
20:29:03.737Z FATAL wings: A fatal error caused the daemon to abort the startup. (additional={})
    Error: No suitable timezone file was located on the system.
        at Async.parallel (/srv/daemon/src/helpers/timezone.js:53:29)
        at /srv/daemon/node_modules/async/dist/async.js:3888:9
        at /srv/daemon/node_modules/async/dist/async.js:473:16
        at iterateeCallback (/srv/daemon/node_modules/async/dist/async.js:992:24)
        at /srv/daemon/node_modules/async/dist/async.js:969:16
        at /srv/daemon/node_modules/async/dist/async.js:3885:13
        at Fs.access.err (/srv/daemon/src/helpers/timezone.js:46:21)
        at FSReqWrap.oncomplete (fs.js:135:15)
20:29:03.737Z ERROR wings: You should forcibly quit this process (CTRL+C) and attempt to fix the issue.


```

**Comment by winadam** [comment]
I made a commit that exposes your systems `/etc/timezone`. This is probably not the best way to do it, but it works for me.
https://github.com/winadam/pterodactyl-docker/commit/036a916a564edd8d1044bf25658f67e20664859d

**Comment by Sporesirius** [comment]
Just add in your core.json under the docker section this:
`    "timezone_path": "/etc/localtime"`

**Comment by ccarney16** [comment]
Ill see about adding that in a later commit, as I have noticed that recently.
