### ISSUE TITLE
Can't get node to connect.

### ISSUE THREAD

**Issue by thierrybla** [ccarney16/pterodactyl-docker#16]
I got my panel running in SSL and made a certificate for both the portal.domain.com and node.domain.com but when I create a node in the portal I can't get it to work at all.

What I do:

1. I create the node in the panel with the domain name I already made a certificate for node.domain.com.

2. I copy the config and paste it in /srv/daemon/config/core.json

3. I edit the core.json and add the correct interface parameter and save the file.

4. I use `docker-compose up -d daemon` and after I see it doesn't work (the node is not connect) I use `docker-compose logs`.

The logs display this:
```
daemon_1   |                  ^
daemon_1   |
daemon_1   | Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/node.domain.com/fullchain.pem'
daemon_1   |     at Object.fs.openSync (fs.js:646:18)
daemon_1   |     at Object.fs.readFileSync (fs.js:551:33)
daemon_1   |     at Object.<anonymous> (/srv/daemon/src/http/restify.js:50:64)
daemon_1   |     at Module._compile (module.js:653:30)
daemon_1   |     at Object.Module._extensions..js (module.js:664:10)
daemon_1   |     at Module.load (module.js:566:32)
daemon_1   |     at tryModuleLoad (module.js:506:12)
daemon_1   |     at Function.Module._load (module.js:498:3)
daemon_1   |     at Module.require (module.js:597:17)
daemon_1   |     at require (internal/module.js:11:18)
daemon_1   |
daemon_1   | > pteronode@0.6.12 start /srv/daemon
daemon_1   | > node src/index.js | node_modules/bunyan/bin/bunyan -o short
daemon_1   |
daemon_1   | 16:59:02.030Z  INFO wings: + ------------------------------------ +
daemon_1   | 16:59:02.032Z  INFO wings: | Running Pterodactyl Daemon v0.6.12   |
daemon_1   | 16:59:02.032Z  INFO wings: |        https://pterodactyl.io        |
daemon_1   | 16:59:02.032Z  INFO wings: |  Copyright 2015 - 2019 Dane Everitt  |
daemon_1   | 16:59:02.032Z  INFO wings: + ------------------------------------ +
daemon_1   | 16:59:02.032Z  INFO wings: Loading modules, this could take a few seconds.
daemon_1   | fs.js:646
daemon_1   |   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
daemon_1   |                  ^
daemon_1   |
daemon_1   | Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/node.domain.com/fullchain.pem'
daemon_1   |     at Object.fs.openSync (fs.js:646:18)
daemon_1   |     at Object.fs.readFileSync (fs.js:551:33)
daemon_1   |     at Object.<anonymous> (/srv/daemon/src/http/restify.js:50:64)
daemon_1   |     at Module._compile (module.js:653:30)
daemon_1   |     at Object.Module._extensions..js (module.js:664:10)
daemon_1   |     at Module.load (module.js:566:32)
daemon_1   |     at tryModuleLoad (module.js:506:12)
daemon_1   |     at Function.Module._load (module.js:498:3)
daemon_1   |     at Module.require (module.js:597:17)
daemon_1   |     at require (internal/module.js:11:18)

```

I am 100% sure that the certificate is located in the location and I also tried connecting the node to the portal.domain.com certificate but both act the same.

If the certificate wouldn't be in the location (as described in the error) it wouldn't work for my panel either right? (since I open my panel on the portal.domain.com address).

Could anyone guide me in the right direct? Did I miss a step? or did I do something wrong?

Thanks in advance!

**Comment by thierrybla** [comment]
This is the config file (core.json)'s content:
```
{
    "web": {
        "host": "0.0.0.0",
        "listen": 8080,
        "ssl": {
            "enabled": true,
            "certificate": "/etc/letsencrypt/live/node.domain.com/fullchain.pem",
            "key": "/etc/letsencrypt/live/node.domain.com/privkey.pem"
        }
    },
    "docker": {
        "container": {
            "user": null
        },
        "network": {
            "name": "pterodactyl_nw"
        },
        "socket": "/var/run/docker.sock",
        "autoupdate_images": true,
        "interfaces": "172.18.0.1"
    },
    "filesystem": {
        "server_logs": "/tmp/pterodactyl"
    },
    "internals": {
        "disk_use_seconds": 30,
        "set_permissions_on_boot": true,
        "throttle": {
            "enabled": true,
            "kill_at_count": 5,
            "decay": 10,
            "lines": 1000,
            "check_interval_ms": 100
        }
    },
    "sftp": {
        "path": "/srv/daemon-data",
        "ip": "0.0.0.0",
        "port": 2022,
        "keypair": {
            "bits": 2048,
            "e": 65537
        }
    },
    "logger": {
        "path": "logs/",
        "src": false,
        "level": "info",
        "period": "1d",
        "count": 3
    },
    "remote": {
        "base": "https://portal.domain.com"
    },
    "uploads": {
        "size_limit": 100
    },
    "keys": [
        "ibTxlxmP7LgZEYEADKAmapQK7mDlADMW0"
    ]
}
```
Keep in mind I did censor my domain name in these examples (its not actually domain.com in the errors and configs)

**Comment by thierrybla** [comment]
Fixed this issue by adding the lines:
```
    - ./letsencrypt:/etc/letsencrypt
    - ./letsencrypt/webroot/.well-known:/var/www/html/public/.well-known
```
to the daemon in the compose file.
