### ISSUE TITLE
500 Internal Error on first-time setup

### ISSUE THREAD

**Issue by humenius** [ccarney16/pterodactyl-docker#31]
I followed the instruction as provided in the INSTALL.md. However, everytime I start up the Docker stack, I receive a 500 error when accessing the frontend. I noticed that for some reason, hostname resolving in docker-compose (for me at least) does not really seem to work correctly(?). The logs always showed up like

```
panel_1   | In PDOConnection.php line 50:
panel_1   |                                                      
panel_1   |   SQLSTATE[HY000] [2006] MySQL server has gone away  
panel_1   |                                                      
panel_1   | 
panel_1   | In PDOConnection.php line 46:
panel_1   |                                                      
panel_1   |   SQLSTATE[HY000] [2006] MySQL server has gone away  
panel_1   |                                                      
panel_1   | 
panel_1   | In PDOConnection.php line 46:
panel_1   |                                                                
panel_1   |   Packets out of order. Expected 0 received 1. Packet size=69
```

which may indicate that MySQL container is not reachable although it's running. Then, I set the MySQL host IP in the `.env` to a IP address that is by provided by the Docker network of the docker-compose file. Afterwards, the error above never showed up, but instead, this stack trace could be found in the logs of Pterodactyl.

```
[2020-01-26 09:56:04] production.ERROR: PDOException: SQLSTATE[HY000] [2002] Operation timed out in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:50
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\Database\Connectors\MySqlConnector->connect
#4 (0): Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(916): call_user_func
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(109): Illuminate\Database\Connection->getPdo
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(93): Illuminate\Database\Connection->createTransaction
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(23): Illuminate\Database\Connection->beginTransaction
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(204): Illuminate\Database\Connection->transaction
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(247): Illuminate\Queue\DatabaseQueue->pop
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(107): Illuminate\Queue\Worker->getNextJob
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker
#14 (0): Illuminate\Queue\Console\WorkCommand->handle
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call
#20 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run
#22 /var/www/html/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run
#23 /var/www/html/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand
#24 /var/www/html/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run
#27 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle
```

Isn't this weird behaviour? 😄

**Comment by NgLoader** [comment]
Check your mysql connection and try to add your pterodactyl network to the mysql container

**Comment by humenius** [comment]
> Check your mysql connection and try to add your pterodactyl network to the mysql container

So it turns out that for some reason, even though environment variables are set, the user for Pterodactyl, as well as the password for the root user do not work. I've had a similiar issue on a different machine in the past. The work around is to use a different MySQL image, e. g. Bitnami's MariaDB image.

I'll close this issue.

P. S. Usually, it's not needed to create a Docker network as docker-compose creates a default one automatically and adds all associated containers to it.
