### ISSUE TITLE
Getting an error 'invalid mount config for type "bind": bind source path does not exist' while trying to change default daemon-data directory

### ISSUE THREAD

**Issue by MedronLinn** [ccarney16/pterodactyl-docker#4]
After following the tutorial for installing pterodactyl-docker, i keep getting an error from the daemon docker when installing a minecraft server.

System : Ubuntu 18.04.1 LTS
From OVH

`docker-compose logs daemon` give that : 
```Attaching to pterodactyl-docker_daemon_1
daemon_1  |
daemon_1  | > pteronode@0.6.8 start /srv/daemon
daemon_1  | > node src/index.js | node_modules/bunyan/bin/bunyan -o short
daemon_1  |
daemon_1  | 19:50:44.560Z  INFO wings: + ------------------------------------ +
daemon_1  | 19:50:44.561Z  INFO wings: | Running Pterodactyl Daemon v0.6.8    |
daemon_1  | 19:50:44.561Z  INFO wings: |        https://pterodactyl.io        |
daemon_1  | 19:50:44.561Z  INFO wings: |  Copyright 2015 - 2018 Dane Everitt  |
daemon_1  | 19:50:44.561Z  INFO wings: + ------------------------------------ +
daemon_1  | 19:50:44.561Z  INFO wings: Loading modules, this could take a few seconds.
daemon_1  | 19:50:44.898Z  INFO wings: Modules loaded, starting Pterodactyl Daemon...
daemon_1  | 19:50:44.917Z  INFO wings: Creating keypair to use for SFTP connections.
daemon_1  | 19:50:45.615Z  INFO wings: Configuring user pterodactyl (id: 500) as the owner of all server files.
daemon_1  | 19:50:45.618Z  INFO wings: Configuring timezone file location...
daemon_1  | 19:50:45.621Z  INFO wings: Checking container networking environment...
daemon_1  | 19:50:45.627Z  WARN wings: No isolated network interface for containers was detected, creating one now.
daemon_1  | 19:51:00.740Z  INFO wings: Successfully created new network (pterodactyl_nw) on pterodactyl0 for isolated containers.
daemon_1  | 19:51:00.740Z  INFO wings: Ensuring correct network interface for containers...
daemon_1  | 19:51:00.751Z  INFO wings: Networking gateway detected as 172.18.1.1 for interface: pterodactyl0.
daemon_1  | 19:51:00.752Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
daemon_1  | 19:51:00.853Z  INFO wings: Checking existing eggs against Panel response...
daemon_1  | 19:51:01.467Z  INFO wings: Beginning server initialization process.
daemon_1  | 19:51:01.469Z  INFO wings: Configuring websocket for daemon stats...
daemon_1  | 19:51:01.470Z  INFO wings: Configuring internal SFTP server...
daemon_1  | 19:51:01.489Z  INFO wings: Pterodactyl Daemon is up-to-date!
daemon_1  | 19:51:01.489Z  INFO wings: Pterodactyl Daemon is now listening for insecure connections on 0.0.0.0:8080
daemon_1  | 19:53:45.350Z  WARN wings: Container was not found. Attempting to recreate it. (server=b825817c-aaac-445b-ad1f-63482e9dbe9c)
daemon_1  | 19:53:45.353Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:java, if so it will happen now.
daemon_1  | 19:53:47.872Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
daemon_1  | 19:53:57.873Z  INFO wings: Pulling image quay.io/pterodactyl/core:java ... this could take a few minutes.
daemon_1  | 19:53:59.935Z FATAL wings: A fatal error was encountered while attempting to create a server.
daemon_1  |     Error: (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /home/daemon-data/b825817c-aaac-445b-ad1f-63482e9dbe9c
daemon_1  |         at /srv/daemon/node_modules/docker-modem/lib/modem.js:254:17
daemon_1  |         at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:7)
daemon_1  |         at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:253:5)
daemon_1  |         at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
daemon_1  |         at emitNone (events.js:111:20)
daemon_1  |         at IncomingMessage.emit (events.js:208:7)
daemon_1  |         at endReadableNT (_stream_readable.js:1064:12)
daemon_1  |         at _combinedTickCallback (internal/process/next_tick.js:139:11)
daemon_1  |         at process._tickDomainCallback (internal/process/next_tick.js:219:9)
daemon_1  | 19:53:59.943Z  INFO wings: Server deleted. (server=b825817c-aaac-445b-ad1f-63482e9dbe9c)
daemon_1  | 19:54:00.063Z  INFO wings: Notified remote panel of server install status.
```

According other github issues relating this error, purging docker solve it, that wasn't the case here.

My core.json (located at /srv/daemon/config/) : 
```
{
  "web": {
    "host": "0.0.0.0",
    "listen": 8080,
    "ssl": {
      "enabled": false,
      "certificate": "/etc/letsencrypt/live/ns3556927.ip-151-80-40.eu/fullchain.pem",
      "key": "/etc/letsencrypt/live/ns3556927.ip-151-80-40.eu/privkey.pem"
    }
  },
  "docker": {
    "container": {
      "user": 500
    },
    "network": {
      "name": "pterodactyl_nw",
      "interfaces": {
        "v4": {
          "subnet": "172.18.1.0/16",
          "gateway": "172.18.1.1"
        }
      }
    },
    "socket": "/var/run/docker.sock",
    "autoupdate_images": true,
    "timezone_path": "/etc/localtime",
    "interface": "172.18.1.1"
  },
  "filesystem": {
    "server_logs": "/tmp/pterodactyl"
  },
  "internals": {
    "disk_use_seconds": 30,
    "set_permissions_on_boot": true,
    "throttle": {
      "enabled": true,
      "kill_at_count": 5,
      "decay": 10,
      "lines": 1000,
      "check_interval_ms": 100
    }
  },
  "sftp": {
    "path": "/home/daemon-data",
    "ip": "0.0.0.0",
    "port": 2022,
    "keypair": {
      "bits": 2048,
      "e": 65537
    }
  },
  "logger": {
    "path": "logs/",
    "src": false,
    "level": "info",
    "period": "1d",
    "count": 3
  },
  "remote": {
    "base": "http://xxx.xxx.eu"
  },
  "uploads": {
    "size_limit": 100
  },
  "keys": [
    "pyUxBwjdYMfc8eygS7F5tRjkOTwX0naq0jIC"
  ]
}
```
Docker info : 
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.5GiB
Name: ns3556927
ID: XAIR:E65C:HWCT:KTXD:A2ES:4YIF:SXSI:D35B:2E2G:U2CN:LLHA:7YBD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by MedronLinn** [comment]
I found the solution, when you have an OVH server, you have also to edit the volume for the daemon, inside the docker-compose.yml.
This way : 
```
    volumes:
    - /srv/daemon/config:/srv/daemon/config
    - /srv/daemon/packs:/srv/daemon/packs
    - /home/daemon-data:/home/daemon-data

    - /tmp/pterodactyl:/tmp/pterodactyl

```

**Comment by ccarney16** [comment]
Yeah, the compose file is mainly a reference, since setups are different. This is meant to reflect a standard setup with as little modifications needed.
