### ISSUE TITLE
"Install script failed with code" when installing server

### ISSUE THREAD

**Issue by padarom** [ccarney16/pterodactyl-docker#5]
After fixing #4 for me whenever I try to install a server the install scripts fail. I tried out different Eggs within the Minecraft Nest, they all failed with code 2. Garry's Mod (see log below) fails with code 127.

Unfortunately due to pterodactyl/panel#1358 I don't see the actual reason why it failed so I don't know if this is pterodactyl-related or related to the docker setup.

System is Ubuntu 16.04 LTS

```
01:43:31.859Z  WARN wings: Container was not found. Attempting to recreate it. (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:43:31.862Z  INFO wings: Checking if we need to update image quay.io/pterodactyl/core:source, if so it will happen now.
01:43:33.604Z  INFO wings: Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.
01:43:43.606Z  INFO wings: Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.
01:43:53.609Z  INFO wings: Pulling image quay.io/pterodactyl/core:source ... this could take a few minutes.
01:43:54.954Z  WARN wings: Server booting is now BLOCKED. (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:43:54.955Z  INFO wings: Blocking server boot until option installation process is completed. (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:43:55.225Z  INFO wings: Writing output of installation process to file. { file: '/srv/daemon/config/servers/91a768fa-5fb1-43f7-a281-ef90ed6c96d3/install.log' } (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:43:56.633Z  INFO wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
01:44:06.634Z  INFO wings: Pulling image ubuntu:16.04 ... this could take a few minutes.
01:44:08.785Z  INFO wings: Temporarily suspending server to avoid mishaps... (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:44:08.794Z  WARN wings: Server has been suspended. (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:44:10.215Z FATAL wings: A fatal error was encountered while attempting to create a server.
    Error: Install script failed with code 127
        at DockerController.run (/srv/daemon/src/controllers/option.js:169:41)
        at /srv/daemon/node_modules/dockerode/lib/docker.js:1417:11
        at /srv/daemon/node_modules/dockerode/lib/container.js:783:7
        at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:270:7)
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:229:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:139:11)
        at process._tickDomainCallback (internal/process/next_tick.js:219:9)
01:44:10.224Z  INFO wings: Server has been unsuspended. (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:44:10.257Z  INFO wings: Server deleted. (server=91a768fa-5fb1-43f7-a281-ef90ed6c96d3)
01:44:10.502Z  INFO wings: Notified remote panel of server install status.
```

**Comment by padarom** [comment]
Found the solution in `pterodactyl/panel#448`.

It was invalid configuration and pretty much the same problem as #4. I mounted /srv/daemon-data and /tmp/pterodactyl to different host directories. Didn't think that the location of these folders on the host mattered but apparently they have to be exactly the same on the daemon and the host machine.
