### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by moracabanas** [ccarney16/pterodactyl-docker#58]
I follow the steps and map /data to local directory so everithing seems to be ok. 

I run it with the following:

`docker run --name=pp -p 80:80 -p 443:443 -d -v /home/--my user---/data:/data --env-file=./.env ccarney16/pterodactyl-panel`

After I set the IP on the browser and try to load the web pannel, it says error 500.

the live docker log output this:

`src:"----my IP----" time:"29/May/2020:05:03:43 +0000" req:"GET / HTTP/1.1" status:"500" agent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" for:"-"
src:"----my IP -----" time:"29/May/2020:05:03:43 +0000" req:"GET /svg/500.svg HTTP/1.1" status:"500" agent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" for:"-"`

And laravel logs output this repetedly:
`production.ERROR: QueryException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve (SQL: select * from information_schem
a.tables where table_schema = pterodactyl and table_name = migrations) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\Database\Schema\MySqlBuilder->hasTable
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(556): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(91): Illuminate\Database\Migrations\Migrator->repositoryExists
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(63): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase
#7 (0): Illuminate\Database\Console\Migrations\MigrateCommand->handle
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call
#13 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run
#15 /var/www/html/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run
#16 /var/www/html/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand
#17 /var/www/html/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run
#20 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle`

I am lost at this time, any help is welcomed thanks.

**Comment by maxfield-allison** [comment]
I'm also encountering this issue both with and without Traefik

**Comment by argetlam-coder** [comment]
You cannot use this image individually. Pterodactyl requires a MySQL database, which is not included in this image. 

The best way is to follow the steps in the wiki (https://github.com/ccarney16/pterodactyl-containers/wiki/Quick-Start). This will create a docker-compose file which contains all needed services.
